	;; Husband Forth character-set codes (mostly ASCII)
_HOME:			equ $01
_LEFT:			equ $08
_RIGHT:			equ $09
_DOWN:			equ $0A
_UP:			equ $0B
_CLS:			equ $0C
_ENTER:			equ $0D
_PUTPAD:		equ $11
_FETCHPAD:		equ $14
_COMPILE:		equ $18
_DELETELINE:		equ $1A
_RUBOUT:		equ $1B
_INSERTLINE:		equ $1C
_EDIT:			equ $1E
_FLASH:			equ $1F
_SPACE:			equ $20
_EXCLAMATION:		equ $21
_QUOTES:		equ $22
_HASH:			equ $23
_DOLLAR:		equ $24
_PERCENT:		equ $25
_AMPERSAND:		equ $26
_QUOTE:			equ $27
_LEFTPARENTH:		equ $28
_RIGHTPARENTH:		equ $29
_ASTERISK:		equ $2A
_PLUS:			equ $2B
_COMMA:			equ $2C
_MINUS:			equ $2D
_PERIOD:		equ $2E
_SLASH:			equ $2F
_0:	 		equ $30
_1:			equ $31
_2:			equ $32
_3:			equ $33
_4:			equ $34
_5:			equ $35
_6:			equ $36
_7:			equ $37
_8:			equ $38
_9:			equ $39
_COLON:			equ $3A
_SEMICOLON:		equ $3B
_LESSTHAN:		equ $3C
_EQUALS:	        equ $3D
_GREATERTHAN:		equ $3E
_QUESTIONMARK:		equ $3F
_AT:			equ $40
_A:			equ $41
_B:			equ $42
_C:			equ $43
_D:			equ $44
_E:			equ $45
_F:			equ $46
_G:			equ $47
_H:	 		equ $48
_I:			equ $49
_J:			equ $4A
_K:			equ $4B
_L:			equ $4C
_M:			equ $4D
_N:			equ $4E
_O:			equ $4F
_P:			equ $50
_Q:			equ $51
_R:			equ $52
_S:			equ $53
_T:			equ $54
_U:			equ $55
_V:			equ $56
_W:			equ $57
_X:			equ $58
_Y:			equ $59
_Z:			equ $5A
_LEFTSQBRACKET:		equ $5B
_RIGHTSQBRACKET:	equ $5D
_BACKSLASH:		equ $5C
_POWER:			equ $5E
_UNDERSCORE:		equ $5F
_BREAK:			equ $80
