( SCREEN 1 - BASIC FUNCTION )

DECIMAL
( DUPLICATE COORDINATES )
: 2DUP OVER OVER ;
: 1+ 1 + ;
: 1- 1 - ;
: PAUSE  S->D TIME D@ + BEGIN 2DUP TIME D@ D< UNTIL ;

( RANDOM NUMBER GENERATOR )
0 VARIABLE SEED
: SEEDON SEED @ 75 U* 0 75 D+
    SWAP OVER OVER U< - -
    1 - DUP SEED ! ;
: RND SEEDON U* DROP ;
: RAND ?DUP 0 = IF 31836 @
	SWAP THEN SEED ! ;
-->

( SCREEN 2 - ARRAY HANDLING )

: ARRAY1 <BUILDS ALLOT DOES> + ; ( SIZE -- | IDX -- )
: ARRAY2 <BUILDS 2DUP C, C, * ALLOT
  DOES> DUP C@ ROT * + + 2 + ;  ( COL ROW -- )
: ARRAYST ( STRLEN STRCNT -- | IDX -- )
    <BUILDS SWAP 1 + SWAP 2DUP C, C, * ALLOT
  DOES> DUP 1+ C@ ROT * + 2 + ;

-->

( SCREEN 3 - GAME DATA )

8 11 ARRAYST BEAST ( BEAST NAMES )
"NOTHING" 0 BEAST W!
"WEREWOLF" 1 BEAST W!
"BUNYIP" 2 BEAST W!
"PHOENIX" 3 BEAST W!
"TROLL" 4 BEAST W!
"GOBLIN" 5 BEAST W!
"GIANT" 6 BEAST W!
"GORGON" 7 BEAST W!
"DRAGON" 8 BEAST W!
"OGRE" 9 BEAST W!
"WIZARD" 10 BEAST W!


( SCREEN 4 - GAME DATA, CONT'D )

9 9 ARRAYST DESC ( ADJECTIVES )
" FIENDIST" 0 DESC W!
" GREEN" 1 DESC W!
" FOUL" 2 DESC W!
" SLIMY" 3 DESC W!
" TOUGH" 4 DESC W!
" HORRIBLE" 5 DESC W!
" HUNGRY" 6 DESC W!
" NASTY" 7 DESC W!
" DIRTY" 8 DESC W!

( SCREEN 5 - TREASURES )

16 8 ARRAYST TREAS ( TREASURE DESCRIPTION )
" 10 SILVER SPOONS" 0 TREAS W!
" A JEWELLED SWORD" 1 TREAS W!
" A JAR OF RUBIES" 2 TREAS W!
" A TREASURE CHEST" 3 TREAS W!
" 50 SILVER PIECES" 4 TREAS W!
" 100 GOLD PIECES" 5 TREAS W!
" A BOX OF JEWELS" 6 TREAS W!
" A FAIR PRINCESS" 7 TREAS W!
8 ARRAY1 TREASV ( VALUE )
10 0 TREASV C! 30 1 TREASV C!
50 2 TREASV C! 200 3 TREASV C!
50 4 TREASV C! 100 5 TREASV C!
75 6 TREASV C! 1 7 TREASV C! 

-->

( SCREEN 6 - GAME SCREENS AND MAP )

0 0 11 11 SCREEN SCRM ( MAP SCREEN )
12 0 31 11 SCREEN SCI ( INSTRUCTIONS )
0 12 31 19 SCREEN SCC ( CONSOLE )
( 0 - CLEAR ; 1 - EXIT ; 2 - SWAMP ; 5 - PLAYER ; 4 - PRINCESS )
6 ARRAY1 MAPLUT 
32 0 MAPLUT C! 43 1 MAPLUT C!
83 2 MAPLUT C! 80 4 MAPLUT C!
88 5 MAPLUT C! 11 11 ARRAY2 MAP

: INITMAP ( -- )
    11 0 DO ( FILL IN BORDER )
	1 I 0 MAP C!
	1 I 10 MAP C!
	1 0 I MAP C!
	1 10 I MAP C!
    LOOP 
    10 1 DO ( FILL IN CENTRE )
	10 1 DO
	    J I MAP
	    10 RND 4 < IF
		2
	    ELSE
		0
	    THEN
	    SWAP C!
	LOOP
    LOOP
;

-->

( SCREEN 7 )

( CARRIAGE RETURN, LINE FEED )
: SCCR 13 OVER .C 10 SWAP .C ;

: PRMAP
    11 0 DO
	11 0 DO
	    I J MAP C@
	    MAPLUT C@
	    SCM .C
	LOOP
	SCM SCCR
    LOOP
;

: IINITPRINCESS
    BEGIN
	3 RND 4 + 3 RND 4 + 2DUP MAP 5 =
    WHILE
	DROP DROP
    REPEAT
    MAP 4 SWAP C!
;

: PRCMPSS 12 SCI .C
    "   N" SCI .W SCI SCCR
    "  W+E" SCI .W SCI SCCR
    "   S" SCI .W SCI SCCR
    " X=YOU" SCI .W SCI SCCR
    " #=SWAMP" SCI .W SCI SCCR
    " #=EDGE" SCI .W SCI SCCR
;
-->

( SCREEN 8 - GAME STATS)
0 VARIABLE MSC
0 VARIABLE INVENT
3 INTEGER ZAP
4 INTEGER PRINCESS
8 INTEGER RING
16 INTEGER WAND
32 INTEGER KNIFE
0 VARIABLE KILLS
0 VARIABLE GEMS
0 VARIABLE BAT
0 VARIABLE STRENGTH

: GET ( OBJECT -- )
    INVENT @ OR INVENT !
;

: HAS ( OBJECT -- FLAG )
    INVENTORY @ AND
;

( SCREEN 9 - MAP INTERACTIONS )
: NOENTRY "TOO WET THAT WAY, CLOT" SCC .W SCC SCCR ;

: FINDPRINCESS "THE PRINCESS COMES WITH YOU" SCC .W SCC SCCR ;

: MV ( COL ROW DCOL DROW -- NCOL NROW FLAG )
    3 PICK + SWAP 4 PICK + SWAP 
    ( ATTEMPT TO UPDATE PLAYER POSITION )
    2DUP MAP C@ DUP 1 = IF
	DROP ROT DROP ROT DROP -1
    ELSE DUP 2 = IF
	    DROP DROP DROP 0
	ELSE DUP 4 = IF PRINCESS GET 
		DROP ROT DROP ROT DROP 1
	    ELSE
		DROP ROT DROP ROT DROP 1
	    THEN
	THEN
    THEN
;

-->

( SCREEN 10 - PLAYER INTERACTIONS )

: RMPLAYER ( COL ROW -- COL ROW )
    ( REMOVE PLAYER FROM MAP )
    2DUP MAP 0 SWAP C!
;

: INPLAYER ( COL ROW -- COL ROW )
    ( ADD PLAYER TO MAP )
    2DUP MAP 5 SWAP C!
;

: MVPLAYER ( COL ROW DCOL DROW -- COL ROW )
    ( MOVE PLAYER AND DEAL WITH CONSEQUENCES )
    MV 0 = IF NOENTRY THEN
    MSG @ ?DUP IF GOTPRINCESS THEN
    INPLAYER
;

( COL ROW -- COL ROW )
( MOVE PLAYER IN DIFFERENT COMPASS DIRECTIONS )
: S  RMPLAYER  0  1 MVPLAYER ;
: N  RMPLAYER  0 -1 MVPLAYER ;
: E  RMPLAYER  1  0 MVPLAYER ;
: W  RMPLAYER -1  0 MVPLAYER ;
: SE RMPLAYER  1  1 MVPLAYER ;
: NE RMPLAYER  1 -1 MVPLAYER ;
: SW RMPLAYER -1  1 MVPLAYER ;
: NW RMPLAYER -1 -1 MVPLAYER ;

-->

( SCREEN 11 )
4 10 ARRAYST CMDS
" N" 0 CMDS W!
" NE" 1 CMDS W!
" E" 2 CMDS W!
" SE" 3 CMDS W!
" S" 4 CMDS W!
" SW" 5 CMDS W!
" W" 6 CMDS W!
" NW" 7 CMDS W!
" OUT" 8 CMDS W!
" MAP" 9 CMDS W!

: GETCMD
    S@
    -1 SWAP 10 0 DO
	I CMDS S= IF
	    SWAP DROP I SWAP LEAVE
	THEN
    LOOP
    CDROP
;	

-->

( SCREEN 12 )

( INITIALISE PLAYER STATS )
: INITPLAYER ( -- COL ROW )
    10 RND 1 + 1 2DUP MAP 5 SWAP C! ( SET LOCN )
    0 KILLS ! ( RESET BEASTS KILLED )
    0 TREASURE ! ( RESET TREASURE )
    0 BAT ! ( DISABLE BAT EFFECT )
    0 INVENT ! ( CARRYING NOTHING )
    1501 RND 500 + STRENGTH ! ( SET INIT STRENGTH )
;

: PIT ( -- )
    40 RND 40 + ( WORK OUT DAMAGE )
    DUP STRENGTH @ 
    SWAP -
    STRENGTH !

    " CLUMSY-YOU JUST FELL INTO A PIT" SCC .W SCC SCCR
    " OF NOISOME WATER" SCC .W SCC SCCR
    " AND USED " SCC .W # SCC .W
    " TO GET OUT " SCC .W SCC SCCR

    STENGTH @ 1 < IF
	" OR WOULD HAVE ..." SCC .W SCC SCCR
	" HAD YOU NOT DROWNED TRYING ..." SCC .W SCCR
	0 STRENGTH !
    THEN
;

( SCREEN 13 )

: THIEF ( -- )
    GEMS @ ?DUP IF ( CHECK IF PLAYER HAS TREASURE )
	2 / GEMS ! ( HALVE IT, IF SO )
	" A SNEAKY THIEF STOLE HALF YOUR" SCC .W SCC SCCR
	" TREASURE...CANT TRUST ANYONE" SCC .W SCC SCCR
    THEN
;

: BATTED ( X Y -- NX NY )
    BAT @ ?DUP IF ( CHECK IF BAT EFFECT IS ACTIVE )
	1 - BAT ! ( DECREMENT BAT COUNTER )
	( PRINT MESSAGE )
	" A GIANT BAT HAS TRANSPORTED YOU" SCC .W SCC SCCR
	" TO ANOTHER PLACE" SCC .W SCC SCCR
	MAP 0 SWAP ! ( CLEAR PLAYER )
	BEGIN 	( FIND NEW LOCATION )
	    7 RND 2 + 7 RND 2 + 2DUP MAP @ 1 -
	WHILE
		DROP DROP
	REPEAT
	2DUP MAP 5 SWAP !
    THEN
;

: MVP ( X Y -- NX NY )
    BEGIN 
	GETCMD DUP -1 = WHILE DROP REPEAT
    UNTIL
    
    CASE N NE E SE S SW W NW OUT PRMAP ;
;

( GOT THIS FAR )
    
: ENCOUNTER ( X Y -- X Y FLAG )
    15 RND     ( CHOOSE MONSTER )

    ( CHECK IF PRINCESS )
    3 PICK 3 PICK MAP C@ 4 = IF
	DROP 10 THEN ( PRINCESS => WIZARD )

    ( CHECK FOR SPECIAL CASES )
    BEGIN
	1 OVER 10 > IF
	    OVER 11 -
	    CASE THIEF PIT BAT EAGLE 1 -
	THEN
    UNTIL

    ( Check for eagle )
    DUP 2 = IF ( DEAL WITH EAGLE ) THEN

      Thief (11)
      Pit (12)
      Bat (13)
      Eagle (14 and S>4) - Exit
    Work out adjectives and print opponent info
    Check for dagger and 9
    Work out treasure
    Check if wizard has a ring
    Fight, bribe, or run
      If fight
        Check have enough strength
	Deduct from strength reserve
	Adjust for gold carried.
	H = 1000, 950, 900, ..., 0
	If L*M <= K and H>=I, Done
	Else repeat
)

( PRINT SPLASH SCREEN )
: SPLASHSCR ( -- )
;

( PRINT INSTRUCTIONS )
: INSTSCR ( -- )
;

    
: SWAMP ( -- )
    0 RAND ( RANDOMIZE GAME )
    SPLASHSCR
    INSTSCR

    ( GAME LOOP )
    BEGIN
	INITPLYR
	INITMAP

	PRINTMAP
	PRINTCMPSS

	BEGIN
	    ( GET DIRN )
	    ( CHECK FOR QUIT )
	    ( CHECK FOR MAP )
	    ( PROCESS DIRN )
	    ( CHECK FOR EXIT )
	    ( CHECK FOR SWAMP )
	WHILE
		( PLAY LOCATION )
		ENCOUNTER
		( ... )
	REPEAT
    UNTIL
;
    

( NOTES )

5 2 ARRAYST STRINGS
" HELLO" 0 STRINGS W!
" BYE" 1 STRINGS W!
1 STRINGS W@ CO .W!

